### PR TITLE
Category bug fix

### LINKED ISSUE #245: Hitting Tab button pulls back the slider
https://youtu.be/ShXkXRJyjzw

### PR DESCRIPTION
**Pull request by choum**
This PR closes #245 and #246 

- Removed code that caused #246 
- Reference error for RC-Slider issue
https://github.com/react-component/slider/issues/433

### CODE REVIEW

File: client-react/src/dashboard/index.js [hunk 1]
```diff
@@ -116,17 +116,13 @@ const Dashboard = () => {
 
   const onTitleChange = (title, i) => {
     const copyCatTitles = [...radarData];
-    copyCatTitles[i].category = title;
+    if (title !== "") {
```
Comment (RyanSW) [inline client-react/src/dashboard/index.js:119]: 😁

**Review by RyanSW — APPROVED** [review]

**Review by Vuologist — APPROVED** [review]
LGTM
