### PR TITLE
added bumpie logo in and fixed margins

### LINKED ISSUE #80: frontend - update signup and login page to match peggy's new designs (2)

### PR DESCRIPTION
**Pull request by choum**
close #80

### CODE REVIEW

File: client-react/src/signin/index.js [hunk 1]
```diff
@@ -133,7 +151,8 @@ const SignIn = () => {
     <CenterContainer>
       <ContentWrapper display={page[0] ? true : false}>
         <LeftContainer img={Polygon} light>
-          <Title>Sign In</Title>
+          <Branding src={logo} alt="logo" />
+          <Title style={{ marginTop: "40px" }}>Sign In</Title>
```
Comment (Vuologist) [inline client-react/src/signin/index.js:155]: rather than doing inline styling. lets pass in a prop and let styled-components handle which style needs to be applied

File: client-react/src/signin/index.js [hunk 2]
```diff
@@ -152,7 +171,10 @@ const SignIn = () => {
       </ContentWrapper>
       <ContentWrapper display={page[1] ? true : false}>
         <LeftContainer smol>
-          <Title light>Welcome!</Title>
+          <Branding style={{ marginTop: "-90px" }} src={logo} alt="logo" />
+          <Title light style={{ marginTop: "60px" }}>
```
Comment (Vuologist) [inline client-react/src/signin/index.js:175]: rather than doing inline styling. lets pass in a prop and let styled-components handle which style needs to be applied

**Review by Vuologist — CHANGES_REQUESTED** [review]

**Review by Vuologist — APPROVED** [review]
